#!/usr/bin/env python3
"""
自动化报告生成器 - $19
"""
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
import os

class ReportGenerator:
    """自动生成数据分析报告"""
    
    def __init__(self, title="Report"):
        self.title = title
        self.sections = []
        self.charts = []
    
    def add_section(self, title, content):
        """添加章节"""
        self.sections.append({'title': title, 'content': content})
    
    def add_chart(self, data, chart_type='bar', title='Chart'):
        """添加图表"""
        self.charts.append({'data': data, 'type': chart_type, 'title': title})
    
    def generate_html(self, output="report.html"):
        """生成 HTML 报告"""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{self.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #333; border-bottom: 2px solid #666; }}
        h2 {{ color: #555; margin-top: 30px; }}
        .content {{ background: #f9f9f9; padding: 20px; border-radius: 8px; }}
        .chart {{ margin: 20px 0; }}
        .footer {{ margin-top: 40px; color: #888; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>{self.title}</h1>
    <p>生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
"""
        
        for section in self.sections:
            html += f"<h2>{section['title']}</h2>"
            html += f"<div class='content'>{section['content']}</div>"
        
        html += """
    <div class="footer">
        Generated by AI Report Generator
    </div>
</body>
</html>
"""
        
        with open(output, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return output
    
    def generate_markdown(self, output="report.md"):
        """生成 Markdown 报告"""
        md = f"# {self.title}\n\n"
        md += f"*生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        
        for section in self.sections:
            md += f"## {section['title']}\n\n"
            md += f"{section['content']}\n\n"
        
        with open(output, 'w', encoding='utf-8') as f:
            f.write(md)
        
        return output

# 示例
if __name__ == "__main__":
    report = ReportGenerator("销售分析报告")
    
    report.add_section("总体概览", "本月销售额增长 15%，达到 100 万元。")
    report.add_section("热销产品", "产品A销量最高，占总销量的 30%。")
    report.add_section("客户分析", "新客户增长 20%，复购率 45%。")
    
    report.generate_html("sales_report.html")
    print("Report generated: sales_report.html")
